ColonyClasses = {}

local function applyBasicStats(playerId, hp, str, mana, dex)
    setPlayerMaxHealth(playerId, hp)
    setPlayerHealth(playerId, hp)
    setPlayerStrength(playerId, str)
    setPlayerMaxMana(playerId, mana)
    setPlayerMana(playerId, mana)
    setPlayerDexterity(playerId, dex)
end

local function applyCommonDefaults(playerId)
    setPlayerTalent(playerId, TALENT_ACROBATIC, 0)
    setPlayerTalent(playerId, TALENT_SNEAK, 1)
    setPlayerTalent(playerId, TALENT_PICK_LOCKS, 1)
    setPlayerTalent(playerId, TALENT_PICKPOCKET, 1)
end

local function equip(playerId, itemInstance)
    giveItem(playerId, itemInstance, 1)
    equipItem(playerId, itemInstance)
end

local function classGuildless(playerId)
    applyBasicStats(playerId, 50, 15, 20, 10)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 10)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 10)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 10)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 10)
    giveItem(playerId, "ItFo_Apple", 1)
    giveItem(playerId, "ITMI_LUTE", 1)
    giveItem(playerId, "ITMI_BROOM", 1)
    giveItem(playerId, "ItFo_Wine", 5)
    giveItem(playerId, "ITMI_RAKE", 1)
    equip(playerId, "ITAR_LEATHER_L")
    equip(playerId, "itmw_1h_bau_mace")
end

local function classFanatic1(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 150, 40, 100, 20)
    setPlayerTalent(playerId, TALENT_MAGE, 3)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 20)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 20)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 20)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 20)
    giveItem(playerId, "ItFo_Apple", 5)
    giveItem(playerId, "ItFo_BOOZE", 5)
    giveItem(playerId, "ItFo_CHEESE", 5)
    giveItem(playerId, "ItFo_BREAD", 5)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 5)
    giveItem(playerId, "ITPO_MANA_ADDON4", 5)
    equip(playerId, "NOV_ARMOR_H")
    equip(playerId, "ITMW_1H_MIL_SWORD")
    giveItem(playerId, "ITMI_SCOOP", 2)
    giveItem(playerId, "ITMI_PAN", 2)
    giveItem(playerId, "ITMI_SAW", 2)
    giveItem(playerId, "ITMI_BROOM", 2)
    giveItem(playerId, "ITMI_RAKE", 2)
    giveItem(playerId, "ITMI_LUTE", 4)
    giveItem(playerId, "ITMI_BRUSH", 2)
    giveItem(playerId, "ITMI_JOINT", 12)
end

local function classFanatic2(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 300, 80, 250, 40)
    setPlayerTalent(playerId, TALENT_MAGE, 3)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 40)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 40)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 20)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 20)
    giveItem(playerId, "ItFo_Apple", 10)
    giveItem(playerId, "ItFo_BOOZE", 10)
    giveItem(playerId, "ItFo_CHEESE", 10)
    giveItem(playerId, "ItFo_BREAD", 10)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 10)
    giveItem(playerId, "ITPO_MANA_ADDON4", 10)
    equip(playerId, "ADDON_FAN_ARMOR_L")
    equip(playerId, "ITMW_STEINBRECHER")
    giveItem(playerId, "ITMI_SCOOP", 2)
    giveItem(playerId, "ITMI_PAN", 2)
    giveItem(playerId, "ITMI_SAW", 2)
    giveItem(playerId, "ITMI_BROOM", 2)
    giveItem(playerId, "ITMI_RAKE", 2)
    giveItem(playerId, "ITMI_LUTE", 4)
    giveItem(playerId, "ITMI_BRUSH", 2)
    giveItem(playerId, "ITMI_JOINT", 12)
end

local function classFanatic3(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 500, 120, 500, 80)
    setPlayerTalent(playerId, TALENT_MAGE, 4)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 50)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 50)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 15)
    giveItem(playerId, "ItFo_BOOZE", 15)
    giveItem(playerId, "ItFo_CHEESE", 15)
    giveItem(playerId, "ItFo_BREAD", 15)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_CHARGEFIREBALL", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 15)
    giveItem(playerId, "ITPO_MANA_ADDON4", 15)
    equip(playerId, "ADDON_NOVFAN_ARMOR_H")
    equip(playerId, "ITMW_KRIEGSHAMMER1")
end

local function classFanatic4(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 650, 160, 800, 120)
    setPlayerTalent(playerId, TALENT_MAGE, 6)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 20)
    giveItem(playerId, "ItFo_BOOZE", 20)
    giveItem(playerId, "ItFo_CHEESE", 20)
    giveItem(playerId, "ItFo_BREAD", 20)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 20)
    giveItem(playerId, "ITPO_MANA_ADDON4", 20)
    equip(playerId, "TPL_ARMOR_M")
    equip(playerId, "ITMW_2H_SWORD_M1")
end

local function classFanatic5(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 350, 80, 100, 70)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 50)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 50)
    giveItem(playerId, "ItFo_Apple", 10)
    giveItem(playerId, "ItFo_Bacon", 10)
    giveItem(playerId, "ItFo_Bread", 2)
    giveItem(playerId, "ItFo_Wine", 10)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 15)
    giveItem(playerId, "ITPO_MANA_ADDON4", 15)
    equip(playerId, "TPL_ARMOR_M")
    equip(playerId, "ITMW_2H_PAL_SWORD")
end

local function classFanatic6(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 500, 100, 200, 90)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 70)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 70)
    giveItem(playerId, "ItFo_Apple", 15)
    giveItem(playerId, "ItFo_Bacon", 15)
    giveItem(playerId, "ItFo_Bread", 5)
    giveItem(playerId, "ItFo_Wine", 15)
    giveItem(playerId, "ItRw_Bolt", 300)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 20)
    giveItem(playerId, "ITPO_MANA_ADDON4", 20)
    giveItem(playerId, "ITRU_ICECUBE", 1)
    giveItem(playerId, "ITRU_MEDIUMHEAL", 1)
    giveItem(playerId, "ITRU_LIGHTNINGFLASH", 1)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_THUNDERBALL", 1)
    equip(playerId, "GUR_ARMOR_M")
end

local function classFanatic7(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 900, 160, 300, 150)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 90)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 90)
    giveItem(playerId, "ItFo_Apple", 25)
    giveItem(playerId, "ItFo_Bacon", 25)
    giveItem(playerId, "ItFo_Bread", 15)
    giveItem(playerId, "ItFo_Wine", 25)
    giveItem(playerId, "ItRw_Bolt", 400)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 30)
    giveItem(playerId, "ITPO_MANA_ADDON4", 30)
    equip(playerId, "ADDON_FAN_ARMOR_H")
    equip(playerId, "ItMw_Addon_PIR2hAxe")
    equip(playerId, "ITRW_CROSSBOW_M2")
end

local function classFanatic8(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 800, 200, 1000, 150)
    setPlayerTalent(playerId, TALENT_MAGE, 6)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 25)
    giveItem(playerId, "ItFo_BOOZE", 25)
    giveItem(playerId, "ItFo_CHEESE", 25)
    giveItem(playerId, "ItFo_BREAD", 25)
    giveItem(playerId, "ITRU_LIGHT", 2)
    giveItem(playerId, "ITRu_Thunderstorm", 1)
    giveItem(playerId, "ITRu_Skull Rune", 1)
    giveItem(playerId, "ITRU_WINDFIST", 1)
    giveItem(playerId, "ITRu_BeliarsRage", 1)
    giveItem(playerId, "ITRU_CONCUSSIONBOLT", 1)
    giveItem(playerId, "ITRU_DEATHBALL", 1)
    giveItem(playerId, "ITRU_DEATHBOLT", 1)
    giveItem(playerId, "ITRU_ICECUBE", 1)
    giveItem(playerId, "ITRU_MEDIUMHEAL", 1)
    giveItem(playerId, "ITRU_LIGHTNINGFLASH", 1)
    giveItem(playerId, "ITRU_THUNDERBALL", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 25)
    giveItem(playerId, "ITPO_MANA_ADDON4", 25)
    equip(playerId, "GUR_ARMOR_H")
end

local function classWaterMage1(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 150, 30, 200, 30)
    setPlayerTalent(playerId, TALENT_MAGE, 1)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 25)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 25)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 25)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 25)
    giveItem(playerId, "ItFo_Apple", 3)
    giveItem(playerId, "ItFo_Water", 3)
    giveItem(playerId, "ITSC_LIGHT", 5)
    giveItem(playerId, "ITSC_ZAP", 5)
    giveItem(playerId, "ITSC_LIGHTMHEAL", 5)
    giveItem(playerId, "ITMI_HAMMER", 1)
    giveItem(playerId, "ITMI_RAKE", 1)
    giveItem(playerId, "ITMI_BROOM", 1)
    giveItem(playerId, "ITMI_LUTE", 1)
    giveItem(playerId, "ITMI_BRUSH", 1)
    giveItem(playerId, "ItPo_Mana_Addon4", 4)
    giveItem(playerId, "ItPo_Health_Addon4", 6)
    equip(playerId, "ITAR_RANGER_Addon")
    equip(playerId, "ITMW_1h_nov_mace")
end

local function classWaterMage2(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 500, 60, 500, 60)
    setPlayerTalent(playerId, TALENT_MAGE, 4)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 30)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 30)
    giveItem(playerId, "ITRU_ICECUBE", 1)
    giveItem(playerId, "ITRU_MEDIUMHEAL", 1)
    giveItem(playerId, "ITRU_LIGHTNINGFLASH", 1)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_THUNDERBALL", 1)
    giveItem(playerId, "ItPo_Mana_Addon4", 15)
    giveItem(playerId, "ItPo_Health_Addon4", 10)
    equip(playerId, "ITAR_KDW_L_Addon")
end

local function classWaterMage3(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 700, 60, 600, 60)
    setPlayerTalent(playerId, TALENT_MAGE, 5)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 30)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 30)
    giveItem(playerId, "ITRU_ICECUBE", 1)
    giveItem(playerId, "ITRU_FULLHEAL", 1)
    giveItem(playerId, "ITRU_LIGHTNINGFLASH", 1)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_THUNDERBALL", 1)
    giveItem(playerId, "ITRU_WINDFIST", 1)
    giveItem(playerId, "ITRU_ICEWAVE", 1)
    giveItem(playerId, "ItPo_Mana_Addon4", 20)
    giveItem(playerId, "ItPo_Health_Addon4", 10)
    equip(playerId, "ITAR_KDW_H")
end

local function classWaterMage4(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 1000, 80, 900, 80)
    setPlayerTalent(playerId, TALENT_MAGE, 6)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 30)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 30)
    giveItem(playerId, "ITRU_ICECUBE", 1)
    giveItem(playerId, "ITRU_FULLHEAL", 1)
    giveItem(playerId, "ITRU_LIGHTNINGFLASH", 1)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_THUNDERBALL", 1)
    giveItem(playerId, "ITRU_WINDFIST", 1)
    giveItem(playerId, "ITRU_ICEWAVE", 1)
    giveItem(playerId, "ITRu_Geyser", 1)
    giveItem(playerId, "ItPo_Mana_Addon4", 20)
    giveItem(playerId, "ItPo_Health_Addon4", 10)
    equip(playerId, "ITAR_KDW_H")
end

local function classFireMage1(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 200, 40, 100, 20)
    setPlayerTalent(playerId, TALENT_MAGE, 1)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 20)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 20)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 5)
    giveItem(playerId, "ItFo_BOOZE", 5)
    giveItem(playerId, "ItFo_CHEESE", 5)
    giveItem(playerId, "ItFo_BREAD", 5)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_FIREBOLT", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 5)
    giveItem(playerId, "ITPO_MANA_ADDON4", 5)
    giveItem(playerId, "ITKE_INNOS_MIS", 1)
    equip(playerId, "ITAR_NOV_L")
    equip(playerId, "ITMW_1H_NOV_MACE")
    giveItem(playerId, "ITMI_SCOOP", 2)
    giveItem(playerId, "ITMI_PAN", 2)
    giveItem(playerId, "ITMI_SAW", 2)
    giveItem(playerId, "ITMI_BROOM", 2)
    giveItem(playerId, "ITMI_RAKE", 2)
    giveItem(playerId, "ITMI_LUTE", 4)
    giveItem(playerId, "ITMI_BRUSH", 2)
end

local function classFireMage2(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 350, 80, 300, 50)
    setPlayerTalent(playerId, TALENT_MAGE, 3)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 40)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 40)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 10)
    giveItem(playerId, "ItFo_BOOZE", 10)
    giveItem(playerId, "ItFo_CHEESE", 10)
    giveItem(playerId, "ItFo_BREAD", 10)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_FIRESTORM", 1)
    giveItem(playerId, "ITRU_INSTANTFIREBALL", 1)
    giveItem(playerId, "ITRU_LIGHTHEAL", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 10)
    giveItem(playerId, "ITPO_MANA_ADDON4", 10)
    giveItem(playerId, "ITKE_INNOS_MIS", 1)
    equip(playerId, "ITAR_KDF_L")
    equip(playerId, "ITMW_ADDON_STAB01")
    giveItem(playerId, "ITMI_SCOOP", 2)
    giveItem(playerId, "ITMI_PAN", 2)
    giveItem(playerId, "ITMI_SAW", 2)
    giveItem(playerId, "ITMI_BROOM", 2)
    giveItem(playerId, "ITMI_RAKE", 2)
    giveItem(playerId, "ITMI_LUTE", 4)
    giveItem(playerId, "ITMI_BRUSH", 2)
end

local function classFireMage3(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 650, 160, 800, 120)
    setPlayerTalent(playerId, TALENT_MAGE, 5)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 20)
    giveItem(playerId, "ItFo_BOOZE", 20)
    giveItem(playerId, "ItFo_CHEESE", 20)
    giveItem(playerId, "ItFo_BREAD", 20)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_SUMWOLF", 1)
    giveItem(playerId, "ITRU_FULLHEAL", 1)
    giveItem(playerId, "ITRU_PYROKINESIS", 1)
    giveItem(playerId, "ITRU_CHARGEFIREBALL", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 20)
    giveItem(playerId, "ITPO_MANA_ADDON4", 20)
    giveItem(playerId, "ITKE_INNOS_MIS", 1)
    equip(playerId, "ITAR_KDF_H")
    equip(playerId, "ITMW_ADDON_STAB05")
end

local function classFireMage4(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 800, 200, 1000, 150)
    setPlayerTalent(playerId, TALENT_MAGE, 6)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 0)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 0)
    giveItem(playerId, "ItFo_Apple", 25)
    giveItem(playerId, "ItFo_BOOZE", 25)
    giveItem(playerId, "ItFo_CHEESE", 25)
    giveItem(playerId, "ItFo_BREAD", 25)
    giveItem(playerId, "ITRU_LIGHT", 1)
    giveItem(playerId, "ITRU_CONCUSSIONBOLT", 1)
    giveItem(playerId, "ITRU_DEATHBALL", 1)
    giveItem(playerId, "ITRU_DEATHBOLT", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 25)
    giveItem(playerId, "ITPO_MANA_ADDON4", 25)
    giveItem(playerId, "ITKE_INNOS_MIS", 1)
    equip(playerId, "ITAR_KDF_H")
    equip(playerId, "ITMW_ADDON_STAB05")
end

local function classOldCamp1(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 100, 40, 200, 30)
    setPlayerTalent(playerId, TALENT_MAGE, 1)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 25)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 25)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 25)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 25)
    giveItem(playerId, "ItFo_Apple", 25)
    giveItem(playerId, "ItFo_Water", 50)
    giveItem(playerId, "ITSC_LIGHTMHEAL", 5)
    giveItem(playerId, "ITMI_LUTE", 1)
    giveItem(playerId, "ItPo_Mana_Addon4", 4)
    giveItem(playerId, "ItPo_Health_Addon4", 6)
    equip(playerId, "VLK_ARMOR_M")
    equip(playerId, "itmw_2h_axe_l1")
end

local function classOldCamp2(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 300, 70, 50, 120)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 40)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 50)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 60)
    giveItem(playerId, "ItFo_Apple", 5)
    giveItem(playerId, "ItFo_Bacon", 5)
    giveItem(playerId, "ItFo_Bread", 1)
    giveItem(playerId, "ItFo_Wine", 5)
    giveItem(playerId, "ItRw_Arrow", 100)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 10)
    giveItem(playerId, "ITPO_MANA_ADDON4", 10)
    equip(playerId, "STT_ARMOR_H")
    equip(playerId, "ITMW_1H_MIL_SWORD")
    equip(playerId, "ITRW_BOW_M4")
end

local function classOldCamp3(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 450, 115, 100, 140)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 60)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 50)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 50)
    giveItem(playerId, "ItFo_Apple", 10)
    giveItem(playerId, "ItFo_Bacon", 10)
    giveItem(playerId, "ItFo_Bread", 2)
    giveItem(playerId, "ItFo_Wine", 10)
    giveItem(playerId, "ItRw_Bolt", 200)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 15)
    giveItem(playerId, "ITPO_MANA_ADDON4", 15)
    equip(playerId, "ADDON_GRD_ARMOR_M1")
    equip(playerId, "itmw_zweihaender1")
    equip(playerId, "ITRW_CROSSBOW_M1")
end

local function classOldCamp4(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 600, 135, 200, 155)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 70)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 70)
    giveItem(playerId, "ItFo_Apple", 15)
    giveItem(playerId, "ItFo_Bacon", 15)
    giveItem(playerId, "ItFo_Bread", 5)
    giveItem(playerId, "ItFo_Wine", 15)
    giveItem(playerId, "ItRw_Bolt", 300)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 20)
    giveItem(playerId, "ITPO_MANA_ADDON4", 20)
    giveItem(playerId, "ITKE_PASS_MIS", 1)
    equip(playerId, "GRD_ARMOR_M")
    equip(playerId, "ITMW_1H_BLESSED1")
    equip(playerId, "ITRW_CROSSBOW_M1")
end

local function classOldCamp5(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 750, 145, 300, 160)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 80)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 80)
    giveItem(playerId, "ItFo_Apple", 20)
    giveItem(playerId, "ItFo_Bacon", 20)
    giveItem(playerId, "ItFo_Bread", 10)
    giveItem(playerId, "ItFo_Wine", 20)
    giveItem(playerId, "ItRw_Bolt", 300)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 25)
    giveItem(playerId, "ITPO_MANA_ADDON4", 25)
    giveItem(playerId, "ITKE_PASS_MIS", 1)
    equip(playerId, "GRD_ARMOR_H")
    equip(playerId, "itmw_zweihaender3")
    equip(playerId, "ITRW_CROSSBOW_M1")
end

local function classOldCamp6(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 1000, 200, 500, 200)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 90)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 90)
    giveItem(playerId, "ItFo_Apple", 30)
    giveItem(playerId, "ItFo_Bacon", 30)
    giveItem(playerId, "ItFo_Bread", 20)
    giveItem(playerId, "ItFo_Wine", 30)
    giveItem(playerId, "ItRw_Bolt", 500)
    giveItem(playerId, "ItMi_Addon_WhitePearl", 10)
    giveItem(playerId, "ITAR_GOVERNOR", 1)
    giveItem(playerId, "ITFO_CHEESE", 30)
    giveItem(playerId, "itmw_1h_special3", 1)
    giveItem(playerId, "ITAR_THORUS_ADDON", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 35)
    giveItem(playerId, "ITPO_MANA_ADDON4", 35)
    giveItem(playerId, "ITKE_PASS_MIS", 1)
    equip(playerId, "ITMW_STURMBRINGER")
    equip(playerId, "ITAR_OreBaron_Addon")
    equip(playerId, "ITRW_CROSSBOW_H1")
end

local function classOldCamp7(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 1300, 200, 500, 200)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 90)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 90)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 90)
    giveItem(playerId, "ItFo_Apple", 30)
    giveItem(playerId, "ItFo_Bacon", 30)
    giveItem(playerId, "ItFo_Bread", 20)
    giveItem(playerId, "ItFo_Wine", 30)
    giveItem(playerId, "ItRw_Bolt", 500)
    giveItem(playerId, "ItMi_Addon_WhitePearl", 10)
    giveItem(playerId, "ITAR_GOVERNOR", 1)
    giveItem(playerId, "ITFO_CHEESE", 30)
    giveItem(playerId, "itmw_1h_special3", 1)
    giveItem(playerId, "ITAR_THORUS_ADDON", 1)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 35)
    giveItem(playerId, "ITPO_MANA_ADDON4", 35)
    giveItem(playerId, "ITKE_PASS_MIS", 1)
    equip(playerId, "ItMw_Drachenschneide")
    equip(playerId, "EBR_ARMOR_H")
    equip(playerId, "ITRW_CROSSBOW_H1")
end

local function classNewCamp1(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 100, 20, 100, 20)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 30)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 30)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 30)
    giveItem(playerId, "ItFo_Apple", 10)
    giveItem(playerId, "ItFo_Bacon", 10)
    giveItem(playerId, "ItFo_Bread", 10)
    giveItem(playerId, "ItFo_Wine", 10)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 10)
    giveItem(playerId, "ITPO_MANA_ADDON4", 10)
    equip(playerId, "itar_bau_l")
    equip(playerId, "itmw_2h_axe_l1")
    giveItem(playerId, "ITMI_LUTE", 2)
end

local function classNewCamp2(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 250, 90, 100, 90)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 50)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 50)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 50)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 50)
    giveItem(playerId, "ItFo_Apple", 15)
    giveItem(playerId, "ItFo_Bacon", 15)
    giveItem(playerId, "ItFo_Bread", 15)
    giveItem(playerId, "ItFo_Wine", 15)
    giveItem(playerId, "ItRw_ARROW", 200)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 15)
    giveItem(playerId, "ITPO_MANA_ADDON4", 15)
    equip(playerId, "ORG_ARMOR_L")
    equip(playerId, "ITMW_BARTAXT")
    equip(playerId, "ITRW_BOW_M1")
    giveItem(playerId, "ITMI_LUTE", 2)
    giveItem(playerId, "ITMI_JOINT", 12)
end

local function classNewCamp3(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 450, 120, 100, 120)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 70)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 70)
    giveItem(playerId, "ItFo_Apple", 20)
    giveItem(playerId, "ItFo_Bacon", 20)
    giveItem(playerId, "ItFo_Bread", 20)
    giveItem(playerId, "ItFo_Wine", 20)
    giveItem(playerId, "ItRw_ARROW", 300)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 20)
    giveItem(playerId, "ITPO_MANA_ADDON4", 20)
    equip(playerId, "ORG_ARMOR_M")
    equip(playerId, "ITMW_KRIEGSHAMMER2")
    equip(playerId, "ITRW_BOW_M3")
    giveItem(playerId, "ITMI_SCOOP", 2)
    giveItem(playerId, "ITMI_PAN", 2)
    giveItem(playerId, "ITMI_SAW", 2)
    giveItem(playerId, "ITMI_BROOM", 2)
    giveItem(playerId, "ITMI_RAKE", 2)
    giveItem(playerId, "ITMI_LUTE", 4)
    giveItem(playerId, "ITMI_BRUSH", 2)
    giveItem(playerId, "ITMI_JOINT", 12)
end

local function classNewCamp4(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 450, 120, 100, 120)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 70)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 70)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 70)
    giveItem(playerId, "ItFo_Apple", 25)
    giveItem(playerId, "ItFo_Bacon", 25)
    giveItem(playerId, "ItFo_Bread", 25)
    giveItem(playerId, "ItFo_Wine", 25)
    giveItem(playerId, "ItRw_ARROW", 400)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 25)
    giveItem(playerId, "ITPO_MANA_ADDON4", 25)
    equip(playerId, "SLD_ARMOR_L")
    equip(playerId, "ITMW_SCHWERT5")
    equip(playerId, "ITRW_BOW_L2")
end

local function classNewCamp5(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 600, 145, 100, 140)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 75)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 75)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 75)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 75)
    giveItem(playerId, "ItFo_Apple", 30)
    giveItem(playerId, "ItFo_Bacon", 30)
    giveItem(playerId, "ItFo_Bread", 30)
    giveItem(playerId, "ItFo_Wine", 30)
    giveItem(playerId, "ITMW_SCHWERT5", 1)
    giveItem(playerId, "ItRw_ARROW", 500)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 30)
    giveItem(playerId, "ITPO_MANA_ADDON4", 30)
    equip(playerId, "SLD_ARMOR_M")
    equip(playerId, "ITMW_SCHLACHTAXT")
    equip(playerId, "ITRW_BOW_M4")
end

local function classNewCamp6(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 700, 160, 100, 160)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 80)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 80)
    giveItem(playerId, "ItFo_Apple", 30)
    giveItem(playerId, "ItFo_Bacon", 30)
    giveItem(playerId, "ItFo_Bread", 30)
    giveItem(playerId, "ITMW_SCHLACHTAXT", 1)
    giveItem(playerId, "ITMW_SCHWERT5", 1)
    giveItem(playerId, "ItRw_ARROW", 500)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 30)
    giveItem(playerId, "ITPO_MANA_ADDON4", 30)
    equip(playerId, "SLD_ARMOR_H")
    equip(playerId, "itmw_barbarenstreitaxt")
    equip(playerId, "ITRW_BOW_H2")
end

local function classNewCamp7(playerId)
    applyCommonDefaults(playerId)
    applyBasicStats(playerId, 1000, 200, 100, 200)
    setPlayerSkillWeapon(playerId, WEAPON_1H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_2H, 80)
    setPlayerSkillWeapon(playerId, WEAPON_BOW, 80)
    setPlayerSkillWeapon(playerId, WEAPON_CBOW, 80)
    giveItem(playerId, "ItFo_Apple", 30)
    giveItem(playerId, "ItFo_Bacon", 30)
    giveItem(playerId, "ItFo_Bread", 30)
    giveItem(playerId, "ITMW_SCHLACHTAXT", 1)
    giveItem(playerId, "ITMW_SCHWERT5", 1)
    giveItem(playerId, "ItRw_ARROW", 500)
    giveItem(playerId, "ITPO_HEALTH_ADDON4", 30)
    giveItem(playerId, "ITPO_MANA_ADDON4", 30)
    equip(playerId, "ITAR_SLD_H")
    equip(playerId, "itmw_berserkeraxt")
    equip(playerId, "ITRW_BOW_H3")
end

ColonyClasses[1]  = { name = "Hobo",                    apply = classGuildless }
ColonyClasses[2]  = { name = "Fanatic Disciple",        apply = classFanatic1 }
ColonyClasses[3]  = { name = "Fanatic Novice",          apply = classFanatic2 }
ColonyClasses[4]  = { name = "Senior Fanatic Novice",   apply = classFanatic3 }
ColonyClasses[5]  = { name = "Sword Disciple",          apply = classFanatic4 }
ColonyClasses[6]  = { name = "Temple Guardian",         apply = classFanatic5 }
ColonyClasses[7]  = { name = "Guru Disciple",           apply = classFanatic6 }
ColonyClasses[8]  = { name = "Sleeper Warior",          apply = classFanatic7 }
ColonyClasses[9]  = { name = "Brotherhood Guru",        apply = classFanatic8 }
ColonyClasses[10] = { name = "Water Novice",            apply = classWaterMage1 }
ColonyClasses[11] = { name = "Water Mage",              apply = classWaterMage2 }
ColonyClasses[12] = { name = "Water Archmage",          apply = classWaterMage3 }
ColonyClasses[13] = { name = "Master Water Mage",       apply = classWaterMage4 }
ColonyClasses[14] = { name = "Fire Novice",             apply = classFireMage1 }
ColonyClasses[15] = { name = "Fire Mage",               apply = classFireMage2 }
ColonyClasses[16] = { name = "Fire Archmage",           apply = classFireMage3 }
ColonyClasses[17] = { name = "Master Fire Mage",        apply = classFireMage4 }
ColonyClasses[18] = { name = "Digger",                  apply = classOldCamp1 }
ColonyClasses[19] = { name = "Shadow",                  apply = classOldCamp2 }
ColonyClasses[20] = { name = "Guard",                   apply = classOldCamp3 }
ColonyClasses[21] = { name = "Experienced Guard",       apply = classOldCamp4 }
ColonyClasses[22] = { name = "Elite Guard",             apply = classOldCamp5 }
ColonyClasses[23] = { name = "Ore Baron",               apply = classOldCamp6 }
ColonyClasses[24] = { name = "Old Camp Leader",         apply = classOldCamp7 }
ColonyClasses[25] = { name = "Scraper",                 apply = classNewCamp1 }
ColonyClasses[26] = { name = "Rogue",                   apply = classNewCamp2 }
ColonyClasses[27] = { name = "Rogues Leader",           apply = classNewCamp3 }
ColonyClasses[28] = { name = "Mercenary",               apply = classNewCamp4 }
ColonyClasses[29] = { name = "Experienced Mercenary",   apply = classNewCamp5 }
ColonyClasses[30] = { name = "Elite Mercenary",         apply = classNewCamp6 }
ColonyClasses[31] = { name = "New Camp Leader",         apply = classNewCamp7 }