CruzerClasses = {
    [0] = {
        name = "Nowy gracz",
        guild = -1,
        stats = { maxHealth = 100, health = 100, strength = 0, dexterity = 0 },
        items = {
            { instance = "ITAR_Leather_L", equip = true },
            { instance = "ItFo_Meat", amount = 10 },
            { instance = "ItFo_Water", amount = 20 },
            { instance = "ItMi_Joint", amount = 3 },
        },
    },
    [1] = {
        name = "Stra?nik miejski",
        guild = 0,
        stats = { maxHealth = 300, health = 300, strength = 60, dexterity = 60 },
        skills = { oneHand = 30, twoHand = 30, bow = 30, crossbow = 30 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Mil_Sword", equip = true },
            { instance = "ITAR_MIL_L", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItKe_Key_01", amount = 1 },
            { instance = "ItKe_Key_02", amount = 1 },
            { instance = "ItKe_Key_03", amount = 1 },
            { instance = "ItLsTorch", amount = 3 },
            { instance = "ItFo_Wine", amount = 10 },
        },
    },
    [2] = {
        name = "Do?wiadczony stra?nik miejski",
        guild = 0,
        stats = { maxHealth = 500, health = 500, strength = 120, dexterity = 120 },
        skills = { oneHand = 60, twoHand = 60, bow = 60, crossbow = 60 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Mil_Sword", equip = true },
            { instance = "ItRw_Crossbow_L_01", equip = true },
            { instance = "ITAR_MIL_M", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItKe_Key_01", amount = 1 },
            { instance = "ItKe_Key_02", amount = 1 },
            { instance = "ItKe_Key_03", amount = 1 },
            { instance = "ItLsTorch", amount = 3 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
        },
    },
    [3] = {
        name = "Rycerz",
        guild = 0,
        stats = { maxHealth = 1000, health = 1000, maxMana = 250, mana = 250, magicLevel = 6, strength = 150, dexterity = 150 },
        skills = { oneHand = 80, twoHand = 80, bow = 75, crossbow = 75 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Pal_Sword", equip = true },
            { instance = "ITAR_PAL_M", equip = true },
            { instance = "ITAR_MIL_M", amount = 1 },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItKe_Key_01", amount = 1 },
            { instance = "ItKe_Key_02", amount = 1 },
            { instance = "ItKe_Key_03", amount = 1 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
            { instance = "ItSc_PalLight", amount = 3 },
            { instance = "ItSc_FullHeal", amount = 3 },
        },
    },
    [4] = {
        name = "Paladyn",
        guild = 0,
        stats = { maxHealth = 1200, health = 1200, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Pal_Sword", equip = true },
            { instance = "ITAR_PAL_H", equip = true },
            { instance = "ITAR_MIL_L", amount = 1 },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItKe_Key_01", amount = 1 },
            { instance = "ItKe_Key_02", amount = 1 },
            { instance = "ItKe_Key_03", amount = 1 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
            { instance = "ItSc_PalLight", amount = 3 },
            { instance = "ItSc_PalLightHeal", amount = 3 },
            { instance = "ItSc_PalHolyBolt", amount = 3 },
            { instance = "ItRu_PalFullHeal", amount = 1 },
            { instance = "ItSc_Firebolt", amount = 30 },
        },
    },
    [5] = {
        name = "Nowicjusz",
        guild = 1,
        stats = { maxHealth = 300, health = 300, maxMana = 100, mana = 100, magicLevel = 6, strength = 50, dexterity = 50 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITAR_NOV_L", equip = true },
            { instance = "ItMw_1h_Nov_Mace", equip = true },
            { instance = "ItRu_Light", amount = 1 },
            { instance = "ItSc_Firebolt", amount = 30 },
            { instance = "ItSc_FullHeal", amount = 3 },
        },
    },
    [6] = {
        name = "Mag ognia",
        guild = 1,
        stats = { maxHealth = 1000, health = 1000, maxMana = 600, mana = 600, magicLevel = 6 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITAR_KDF_L", equip = true },
            { instance = "ItRu_Light", amount = 1 },
            { instance = "ItRu_Firebolt", amount = 1 },
            { instance = "ItRu_Icebolt", amount = 1 },
            { instance = "ItRu_Windfist", amount = 1 },
            { instance = "ItRu_Sleep", amount = 1 },
            { instance = "ItAr_Dementor", amount = 1 },
            { instance = "ItPo_Mana_03", amount = 20 },
            { instance = "ItPo_Speed", amount = 3 },
        },
    },
    [7] = {
        name = "Cz?onek kr?gu ognia",
        guild = 1,
        stats = { maxHealth = 1300, health = 1300, maxMana = 1000, mana = 1000, magicLevel = 6 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITAR_KDF_H", equip = true },
            { instance = "ItRu_Light", amount = 1 },
            { instance = "ItRu_Firebolt", amount = 1 },
            { instance = "ItRu_Icebolt", amount = 1 },
            { instance = "ItRu_Windfist", amount = 1 },
            { instance = "ItRu_Sleep", amount = 1 },
            { instance = "ItRu_Firerain", amount = 1 },
            { instance = "ItAr_Dementor", amount = 1 },
            { instance = "ItPo_Mana_03", amount = 20 },
            { instance = "ItRu_InstantFireball", amount = 1 },
            { instance = "ItPo_Speed", amount = 3 },
        },
    },
    [8] = {
        name = "Najemnik",
        guild = 2,
        stats = { maxHealth = 300, health = 300, strength = 60, dexterity = 60 },
        skills = { oneHand = 30, twoHand = 30, bow = 30, crossbow = 30 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_1H_Sword_L_03", equip = true },
            { instance = "ITAR_SLD_L", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Cheese", amount = 2 },
            { instance = "ItLsTorch", amount = 5 },
            { instance = "ItFo_Wine", amount = 10 },
        },
    },
    [9] = {
        name = "Uzbrojony najemnik",
        guild = 2,
        stats = { maxHealth = 500, health = 500, strength = 120, dexterity = 120 },
        skills = { oneHand = 60, twoHand = 60, bow = 60, crossbow = 60 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_1h_Sld_Sword", equip = true },
            { instance = "ItRw_Crossbow_L_01", equip = true },
            { instance = "ITAR_SLD_M", equip = true },
            { instance = "ItMi_Joint", amount = 12 },
            { instance = "ItFo_Apple", amount = 4 },
            { instance = "ItLsTorch", amount = 3 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
        },
    },
    [10] = {
        name = "Do?wiadczony najemnik",
        guild = 2,
        stats = { maxHealth = 1200, health = 1200, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_ShortSword4", equip = true },
            { instance = "ITAR_SLD_H", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ItRu_PalLight", amount = 1 },
        },
    },
    [11] = {
        name = "Lord miasta Khorinis",
        guild = 0,
        stats = { maxHealth = 1600, health = 1600, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_Schwert5", equip = true },
            { instance = "ITAR_Governor", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ItRu_PalLight", amount = 1 },
            { instance = "ItRu_InstantFireBall", amount = 1 },
        },
    },
    [12] = {
        name = "?owca smoków",
        guild = 2,
        stats = { maxHealth = 1600, health = 1600, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_Schwert5", equip = true },
            { instance = "ITAR_DJG_L", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ItRu_PalLight", amount = 1 },
            { instance = "ItRu_InstantFireBall", amount = 1 },
        },
    },
    [13] = {
        name = "Urz?dnik",
        guild = 0,
        stats = { maxHealth = 1600, health = 1600, strength = 100, dexterity = 100 },
        skills = { oneHand = 25, twoHand = 25, bow = 0, crossbow = 0 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_1h_Vlk_Dagger", equip = true },
            { instance = "ITAR_Governor", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ITAR_VLK_L", amount = 1 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
        },
    },
    [14] = {
        name = "Obywatel",
        guild = 0,
        stats = { maxHealth = 200, health = 200, strength = 10, dexterity = 10 },
        skills = { oneHand = 20, twoHand = 20, bow = 0, crossbow = 0 },
        items = {
            { instance = "ItMw_1h_Vlk_Dagger", equip = true },
            { instance = "ITAR_VLK_L", equip = true },
            { instance = "ITAR_VLKBABE_H", amount = 1 },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItLsTorch", amount = 1 },
            { instance = "ItFo_Bacon", amount = 12 },
        },
    },
    [15] = {
        name = "Kowal",
        guild = 0,
        stats = { maxHealth = 500, health = 500, strength = 40, dexterity = 40 },
        skills = { oneHand = 30, twoHand = 30, bow = 0, crossbow = 0 },
        items = {
            { instance = "ItMw_1h_Mace_L_04", equip = true },
            { instance = "ITAR_SMITH", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItLsTorch", amount = 1 },
            { instance = "ItFo_Bacon", amount = 12 },
            { instance = "ItMiSwordraw", amount = 100 },
        },
    },
    [16] = {
        name = "Chemik",
        guild = 0,
        stats = { maxHealth = 400, health = 400, strength = 40, dexterity = 40 },
        skills = { oneHand = 30, twoHand = 30, bow = 0, crossbow = 0 },
        items = {
            { instance = "ItMw_1h_Bau_Axe", equip = true },
            { instance = "ITAR_SMITH", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItLsTorch", amount = 1 },
            { instance = "ItFo_Bacon", amount = 12 },
            { instance = "ItPo_Speed", amount = 5 },
            { instance = "ItPl_SwampHerb", amount = 3 },
            { instance = "ItPl_Mana_Herb_02", amount = 3 },
            { instance = "ItPl_Health_Herb_03", amount = 3 },
            { instance = "ItPl_Dex_Herb_01", amount = 3 },
            { instance = "ItPl_Strength_Herb_01", amount = 3 },
            { instance = "ItPl_Speed_Herb_01", amount = 3 },
            { instance = "ItPl_Blueplant", amount = 3 },
            { instance = "ItMi_Flask", amount = 5 },
        },
    },
    [17] = {
        name = "Farmer",
        guild = 2,
        stats = { maxHealth = 300, health = 300, strength = 20, dexterity = 20 },
        skills = { oneHand = 30, twoHand = 30, bow = 0, crossbow = 0 },
        items = {
            { instance = "ItMw_1h_Mace_L_04", equip = true },
            { instance = "ITAR_BAU_M", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Rake", amount = 1 },
            { instance = "ItMi_Scoop", amount = 1 },
            { instance = "ItMi_Broom", amount = 1 },
            { instance = "ItMi_Brush", amount = 1 },
            { instance = "ItFo_Bacon", amount = 2 },
        },
    },
    [18] = {
        name = "S?dzia",
        guild = 0,
        stats = { maxHealth = 1600, health = 1600, strength = 100, dexterity = 100 },
        skills = { oneHand = 25, twoHand = 25, bow = 0, crossbow = 0 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_1h_Vlk_Dagger", equip = true },
            { instance = "ITAR_Judge", equip = true },
            { instance = "ITAR_Governor", amount = 1 },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ITAR_VLK_L", amount = 1 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
        },
    },
    [19] = {
        name = "Cienias",
        guild = 3,
        stats = { maxHealth = 300, health = 300, strength = 60, dexterity = 60 },
        skills = { oneHand = 30, twoHand = 30, bow = 30, crossbow = 30 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Mil_Sword", equip = true },
            { instance = "ItRw_Bow_L_01", equip = true },
            { instance = "ITAR_BDT_M", equip = true },
            { instance = "ItMi_Joint", amount = 16 },
            { instance = "ITAR_Leather_L", amount = 1 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItLsTorch", amount = 3 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Arrow", amount = 100 },
        },
    },
    [20] = {
        name = "Bandyta",
        guild = 3,
        stats = { maxHealth = 500, health = 500, strength = 120, dexterity = 120 },
        skills = { oneHand = 60, twoHand = 60, bow = 60, crossbow = 60 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Mil_Sword", equip = true },
            { instance = "ItRw_Crossbow_L_01", equip = true },
            { instance = "ItAr_BDT_H", equip = true },
            { instance = "ITAR_Leather_L", amount = 1 },
            { instance = "ItMi_Joint", amount = 26 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItLsTorch", amount = 3 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
        },
    },
    [21] = {
        name = "Bandyta (stra?nik)",
        guild = 3,
        stats = { maxHealth = 1000, health = 1000, maxMana = 250, mana = 250, magicLevel = 6, strength = 150, dexterity = 150 },
        skills = { oneHand = 80, twoHand = 80, bow = 75, crossbow = 75 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Pal_Sword", equip = true },
            { instance = "ITAR_THORUS_ADDON", equip = true },
            { instance = "ITAR_Leather_L", amount = 1 },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
        },
    },
    [22] = {
        name = "Herszt bandytów",
        guild = 3,
        stats = { maxHealth = 1200, health = 1200, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Militia.mds",
        items = {
            { instance = "ItMw_1h_Pal_Sword", equip = true },
            { instance = "ITAR_Raven_Addon", equip = true },
            { instance = "ITRW_CROSSBOW_H_02", equip = true },
            { instance = "ITAR_VLK_L", amount = 1 },
            { instance = "ITAR_MIL_L", amount = 1 },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Bolt", amount = 25 },
            { instance = "ItSc_PalLight", amount = 3 },
            { instance = "ItSc_PalLightHeal", amount = 3 },
            { instance = "ItSc_PalHolyBolt", amount = 3 },
            { instance = "ItRu_PalFullHeal", amount = 1 },
            { instance = "ItSc_Firebolt", amount = 30 },
        },
    },
    [23] = {
        name = "Król (V0ID)",
        guild = 0,
        stats = { maxHealth = 1600, health = 1600, maxMana = 1000, mana = 1000, magicLevel = 6, strength = 400, dexterity = 400 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "Humans_Relaxed.mds",
        items = {
            { instance = "ItMw_ElBastardo", equip = true },
            { instance = "ITAR_Governor", equip = true },
            { instance = "ITAR_Bloodwyn_Addon", amount = 1 },
            { instance = "ITAR_Barkeeper", amount = 1 },
            { instance = "ITAR_KDF_H", amount = 1 },
            { instance = "ITMI_INNOSEYE_MIS", amount = 1 },
            { instance = "ITAR_RANGER_Addon", amount = 1 },
            { instance = "ItRu_Light", amount = 1 },
            { instance = "ItRu_Firebolt", amount = 1 },
            { instance = "ItRu_Icebolt", amount = 1 },
            { instance = "ItRu_Windfist", amount = 1 },
            { instance = "ItRu_Sleep", amount = 1 },
            { instance = "ItRu_Firerain", amount = 1 },
            { instance = "ItAr_Dementor", amount = 1 },
            { instance = "ItPo_Mana_03", amount = 20 },
            { instance = "ItRu_InstantFireball", amount = 1 },
            { instance = "ItPo_Speed", amount = 3 },
        },
    },
    [24] = {
        name = "?uczarz",
        guild = 0,
        stats = { maxHealth = 300, health = 300, strength = 60, dexterity = 60 },
        skills = { oneHand = 30, twoHand = 30, bow = 30, crossbow = 30 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMw_1h_Mil_Sword", equip = true },
            { instance = "ItRw_Bow_L_01", equip = true },
            { instance = "ITAR_Leather_L", equip = true },
            { instance = "ItMi_Joint", amount = 16 },
            { instance = "ITAR_Leather_L", amount = 1 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItLsTorch", amount = 3 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItRw_Arrow", amount = 1000 },
            { instance = "ITRW_BOLT", amount = 1000 },
            { instance = "ITRW_BOW_H_01", amount = 1 },
            { instance = "ITRW_BOW_H_02", amount = 1 },
            { instance = "ITRW_BOW_H_03", amount = 1 },
            { instance = "ITRW_BOW_L_01", amount = 1 },
            { instance = "ITRW_BOW_L_02", amount = 1 },
            { instance = "ITRW_BOW_L_03", amount = 1 },
            { instance = "ITRW_SLD_BOW", amount = 1 },
            { instance = "ITRW_CROSSBOW_H_01", amount = 1 },
            { instance = "ITRW_CROSSBOW_H_02", amount = 1 },
            { instance = "ITRW_MIL_CROSSBOW", amount = 1 },
            { instance = "ITRW_CROSSBOW_M_02", amount = 1 },
        },
    },
    [25] = {
        name = "Genera?",
        guild = 0,
        stats = { maxHealth = 1300, health = 1300, maxMana = 1000, mana = 1000, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "Humans_Relaxed.mds",
        items = {
            { instance = "ItMw_1H_Blessed_02", equip = true },
            { instance = "itar_orebaron_addon", equip = true },
            { instance = "itar_pal_h", amount = 1 },
            { instance = "ITAR_Barkeeper", amount = 1 },
            { instance = "ItRu_Light", amount = 1 },
            { instance = "ItRu_Icebolt", amount = 1 },
            { instance = "ItRu_Windfist", amount = 1 },
            { instance = "ItAr_Dementor", amount = 1 },
            { instance = "ItPo_Mana_03", amount = 20 },
            { instance = "ItRu_InstantFireball", amount = 1 },
            { instance = "ItPo_Speed", amount = 3 },
        },
    },
    [26] = {
        name = "Pacho?ek cienia",
        guild = 4,
        stats = { maxHealth = 300, health = 300, maxMana = 200, mana = 200, magicLevel = 6, strength = 35, dexterity = 35 },
        skills = { oneHand = 20, twoHand = 20, bow = 0, crossbow = 0 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITMW_1H_SWORD_L_03", equip = true },
            { instance = "ITAR_LESTER", equip = true },
            { instance = "itpo_perm_mana", amount = 20 },
            { instance = "ITRU_FIREBOLT", amount = 1 },
            { instance = "ITRU_ZAP", amount = 1 },
            { instance = "ITFO_FISH", amount = 1 },
            { instance = "ITFO_APPLE", amount = 1 },
            { instance = "ITFO_WATER", amount = 1 },
        },
    },
    [27] = {
        name = "Cz?onek bractwa",
        guild = 4,
        stats = { maxHealth = 400, health = 400, maxMana = 200, mana = 200, magicLevel = 6, strength = 60, dexterity = 70 },
        skills = { oneHand = 40, twoHand = 40, bow = 0, crossbow = 0 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITMW_HELLEBARDE", equip = true },
            { instance = "itar_mayazombie_addon", equip = true },
            { instance = "itpo_perm_mana", amount = 20 },
            { instance = "itpo_perm_health", amount = 20 },
            { instance = "ITRU_FIREBOLT", amount = 1 },
            { instance = "ITRU_ZAP", amount = 1 },
            { instance = "ITFO_FISH", amount = 1 },
            { instance = "ITFO_APPLE", amount = 1 },
            { instance = "ITFO_WATER", amount = 1 },
            { instance = "ITRU_WINDFIST", amount = 1 },
            { instance = "ITFO_SAUSAGE", amount = 1 },
            { instance = "ITFO_CHEESE", amount = 1 },
            { instance = "ITMI_JOINT", amount = 3 },
        },
    },
    [28] = {
        name = "Wojownik mroku",
        guild = 4,
        stats = { maxHealth = 700, health = 700, maxMana = 800, mana = 800, magicLevel = 6, strength = 100, dexterity = 80 },
        skills = { oneHand = 60, twoHand = 60, bow = 0, crossbow = 0 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITMW_2H_ORCAXE_03", equip = true },
            { instance = "ITAR_CORANGAR", equip = true },
            { instance = "itpo_perm_mana", amount = 20 },
            { instance = "itpo_perm_health", amount = 20 },
            { instance = "ITRU_FIREBOLT", amount = 1 },
            { instance = "ITRU_ZAP", amount = 1 },
            { instance = "ITFO_FISH", amount = 1 },
            { instance = "ITFO_APPLE", amount = 1 },
            { instance = "ITFO_WATER", amount = 1 },
            { instance = "ITRU_WINDFIST", amount = 1 },
            { instance = "ITFO_SAUSAGE", amount = 1 },
            { instance = "ITFO_CHEESE", amount = 1 },
            { instance = "ITMI_JOINT", amount = 3 },
            { instance = "ITRU_LIGHTHEAL", amount = 1 },
            { instance = "ITRU_FIRESTORM", amount = 1 },
            { instance = "ITRU_ICECUBE", amount = 1 },
        },
    },
    [29] = {
        name = "Nekromanta",
        guild = 4,
        stats = { maxHealth = 1000, health = 1000, maxMana = 1200, mana = 1200, magicLevel = 6, strength = 80, dexterity = 80 },
        skills = { oneHand = 0, twoHand = 0, bow = 0, crossbow = 0 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITAR_XARDAS", equip = true },
            { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
            { instance = "itpo_perm_mana", amount = 20 },
            { instance = "itpo_perm_health", amount = 20 },
            { instance = "ITRU_PYROKINESIS", amount = 1 },
            { instance = "ITSC_PALHOLYBOLT", amount = 1 },
            { instance = "ITSC_PALREPELEVIL", amount = 1 },
            { instance = "ITFO_FISH", amount = 1 },
            { instance = "ITFO_APPLE", amount = 1 },
        },
    },
    [30] = {
        name = "Cie?",
        guild = 4,
        stats = { maxHealth = 1100, health = 1100, maxMana = 1200, mana = 1200, magicLevel = 6, strength = 120, dexterity = 80 },
        skills = { oneHand = 80, twoHand = 80, bow = 0, crossbow = 0 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "itmw_2h_blessed_03", equip = true },
            { instance = "ITAR_DEMENTOR", equip = true },
            { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
            { instance = "itpo_perm_mana", amount = 20 },
            { instance = "itpo_perm_health", amount = 20 },
            { instance = "ITRU_PYROKINESIS", amount = 1 },
            { instance = "ITSC_PALHOLYBOLT", amount = 1 },
            { instance = "ITSC_PALREPELEVIL", amount = 1 },
            { instance = "ITFO_FISH", amount = 1 },
            { instance = "ITFO_APPLE", amount = 1 },
            { instance = "ITRU_ICEWAVE", amount = 1 },
            { instance = "ITRU_SLEEP", amount = 1 },
        },
    },
    [31] = {
        name = "Kap?an",
        guild = 4,
        stats = { maxHealth = 1300, health = 1300, maxMana = 2000, mana = 2000, magicLevel = 6, strength = 160, dexterity = 160 },
        skills = { oneHand = 100, twoHand = 100, bow = 100, crossbow = 100 },
        baseOverlay = "Humans_Mage.mds",
        items = {
            { instance = "ITMW_2H_SPECIAL_02", equip = true },
            { instance = "ITAR_DJG_H", equip = true },
            { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
            { instance = "itpo_perm_mana", amount = 20 },
            { instance = "itpo_perm_health", amount = 20 },
            { instance = "ITRU_PYROKINESIS", amount = 1 },
            { instance = "ITSC_PALHOLYBOLT", amount = 1 },
            { instance = "ITSC_PALREPELEVIL", amount = 1 },
            { instance = "ITFO_FISH", amount = 1 },
            { instance = "ITFO_APPLE", amount = 1 },
            { instance = "ITRU_ICEWAVE", amount = 1 },
            { instance = "ITRU_FULLHEAL", amount = 1 },
            { instance = "ITRU_HARMUNDEAD", amount = 1 },
            { instance = "ITRU_FIRERAIN", amount = 1 },
            { instance = "ITFOMUTTONRAW", amount = 1 },
            { instance = "itpo_speed", amount = 10 },
            { instance = "ITAT_DRAGONBLOOD", amount = 1 },
            { instance = "ITAR_VLKBABE_M", amount = 1 },
            { instance = "ITAR_VLK_M", amount = 1 },
            { instance = "ITFO_BREAD", amount = 1 },
            { instance = "ITFO_MILK", amount = 1 },
            { instance = "ITMI_RUNEBLANK", amount = 1 },
            { instance = "ITMI_JOINT", amount = 20 },
            { instance = "ITFO_WINE", amount = 1 },
            { instance = "ITAT_DEMONHEART", amount = 1 },
            { instance = "ITAT_GOBLINBONE", amount = 1 },
            { instance = "ITRW_BOW_H_01", amount = 1 },
            { instance = "ITRW_ARROW", amount = 100 },
        },
    },
    [32] = {
        name = "Lord Kossak",
        guild = 5,
        stats = { maxHealth = 1500, health = 1500, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ItMW_meisterdegen", equip = true },
            { instance = "ITAR_pal_skel", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITAT_DRGSNAPPERHORN", amount = 1 },
            { instance = "ITAR_Governor", amount = 1 },
        },
    },
    [33] = {
        name = "Prawa r?ka (Kossak)",
        guild = 5,
        stats = { maxHealth = 1000, health = 1000, maxMana = 500, mana = 500, magicLevel = 6, strength = 150, dexterity = 200 },
        skills = { oneHand = 60, twoHand = 60, bow = 60, crossbow = 60 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ITMW_2H_ORCAXE_04", equip = true },
            { instance = "ITAR_djg_crawler", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITRW_CROSSBOW_H_01", amount = 1 },
            { instance = "ITAT_WOLFFUR", amount = 10 },
            { instance = "ITAT_SHADOWHORN", amount = 1 },
            { instance = "ITRW_BOLT", amount = 25 },
        },
    },
    [34] = {
        name = "?o?nierz (Kossak)",
        guild = 5,
        stats = { maxHealth = 750, health = 750, maxMana = 500, mana = 500, magicLevel = 6, strength = 75, dexterity = 200 },
        skills = { oneHand = 35, twoHand = 35, bow = 35, crossbow = 35 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ITMW_2H_ORCAXE_02", equip = true },
            { instance = "ITAR_bloodwyn_addon", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITRW_CROSSBOW_M_01", amount = 1 },
            { instance = "ITAT_WOLFFUR", amount = 10 },
            { instance = "ITAT_TEETH", amount = 10 },
            { instance = "ITRW_BOLT", amount = 25 },
        },
    },
    [35] = {
        name = "Farmer (Kossak)",
        guild = 5,
        stats = { maxHealth = 500, health = 500, maxMana = 500, mana = 500, magicLevel = 6, strength = 75, dexterity = 200 },
        skills = { oneHand = 35, twoHand = 35, bow = 35, crossbow = 35 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "Itmw_1h_misc_axe", equip = true },
            { instance = "ITAR_PRISONER", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITMI_BROOM", amount = 1 },
            { instance = "ITRW_BOW_L_01", amount = 10 },
            { instance = "ITAT_TEETH", amount = 10 },
            { instance = "ITRW_ARROW", amount = 25 },
        },
    },
    [36] = {
        name = "Lord Randall",
        guild = 6,
        stats = { maxHealth = 1600, health = 1600, maxMana = 500, mana = 500, magicLevel = 6, strength = 200, dexterity = 200 },
        skills = { oneHand = 100, twoHand = 100, bow = 80, crossbow = 80 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "Itmw_kriegshammer2", equip = true },
            { instance = "itar_raven_addon", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ItRu_PalLight", amount = 1 },
            { instance = "ITAR_Governor", amount = 1 },
        },
    },
    [37] = {
        name = "Prawa r?ka (Randall)",
        guild = 6,
        stats = { maxHealth = 1000, health = 1000, maxMana = 500, mana = 500, magicLevel = 6, strength = 150, dexterity = 200 },
        skills = { oneHand = 60, twoHand = 60, bow = 60, crossbow = 60 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ITMW_FOLTERAXT", equip = true },
            { instance = "ITAR_CORANGAR", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITRW_BOW_H_03", amount = 1 },
            { instance = "ITAT_WOLFFUR", amount = 10 },
            { instance = "ITMI_GOLDCUP", amount = 1 },
            { instance = "ITRW_ARROW", amount = 25 },
        },
    },
    [38] = {
        name = "?o?nierz (Randall)",
        guild = 6,
        stats = { maxHealth = 750, health = 750, maxMana = 500, mana = 500, magicLevel = 6, strength = 75, dexterity = 200 },
        skills = { oneHand = 35, twoHand = 35, bow = 35, crossbow = 35 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ITMW_KRUMMSCHWERT", equip = true },
            { instance = "ITAR_RANGER_Addon", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITRW_BOW_H_02", amount = 1 },
            { instance = "ITAT_WOLFFUR", amount = 10 },
            { instance = "ITMI_SILVERCUP", amount = 1 },
            { instance = "ITRW_ARROW", amount = 25 },
        },
    },
    [39] = {
        name = "Farmer (Randall)",
        guild = 6,
        stats = { maxHealth = 500, health = 500, maxMana = 500, mana = 500, magicLevel = 6, strength = 75, dexterity = 200 },
        skills = { oneHand = 35, twoHand = 35, bow = 35, crossbow = 35 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ITMW_1H_SWORD_L_03", equip = true },
            { instance = "ITAR_BARKEEPER", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITMI_BROOM", amount = 1 },
            { instance = "ITRW_BOW_L_01", amount = 10 },
            { instance = "ITAT_TEETH", amount = 10 },
            { instance = "ITRW_ARROW", amount = 25 },
        },
    },
    [40] = {
        name = "Uczony (Kossak)",
        guild = 5,
        stats = { maxHealth = 500, health = 500, maxMana = 500, mana = 500, magicLevel = 6, strength = 75, dexterity = 200 },
        skills = { oneHand = 35, twoHand = 35, bow = 35, crossbow = 35 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "ITMW_KRIEGSKEULE", equip = true },
            { instance = "ITAR_vlk_h", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITMI_BROOM", amount = 1 },
            { instance = "ITRW_BOW_L_01", amount = 10 },
            { instance = "ITAT_TEETH", amount = 10 },
            { instance = "ITMI_GOLDNECKLACE", amount = 1 },
        },
    },
    [41] = {
        name = "Uczony (Randall)",
        guild = 6,
        stats = { maxHealth = 500, health = 500, maxMana = 500, mana = 500, magicLevel = 6, strength = 75, dexterity = 200 },
        skills = { oneHand = 35, twoHand = 35, bow = 35, crossbow = 35 },
        baseOverlay = "HumanS_Relaxed.mds",
        items = {
            { instance = "itmw_1h_vlk_sword", equip = true },
            { instance = "ITAR_judge", equip = true },
            { instance = "ItMi_Joint", amount = 6 },
            { instance = "ItFo_Apple", amount = 2 },
            { instance = "ItFo_Wine", amount = 10 },
            { instance = "ItMi_Lute", amount = 1 },
            { instance = "ItMi_Sextant", amount = 1 },
            { instance = "ITMI_BROOM", amount = 1 },
            { instance = "ITRW_BOW_L_01", amount = 10 },
            { instance = "ITAT_TEETH", amount = 10 },
            { instance = "ITMI_GOLDNECKLACE", amount = 1 },
        },
    },
}
