Classic = {}

Classic.previewVirtualWorldBase = 1000
Classic.selectorPlayerPosition = { x = 0, y = 0, z = 0, angle = 180 }

Classic.classes = {
  {
    name = "Wanderer",
    description = "A self-reliant drifter with a dagger, bow and enough supplies to keep moving.",
    team = "None",
    strength = 20,
    dexterity = 30,
    mana = 0,
    health = 180,
    skills = {
      [WEAPON_1H] = 15,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 20,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 37376.2, y = 3868.62, z = -3943.54, angle = 15 },
    armor = "ITAR_LEATHER_L",
    primary = "ITMW_1H_VLK_DAGGER",
    secondary = "ITRW_BOW_L_01",
    items = {
      { instance = "ITRW_ARROW", amount = 25 },
      { instance = "ITKE_LOCKPICK", amount = 2 },
      { instance = "ITLSTORCH", amount = 2 },
      { instance = "ITFO_BREAD", amount = 4 },
      { instance = "ITFO_CHEESE", amount = 2 },
      { instance = "ITFO_APPLE", amount = 3 },
      { instance = "ITFO_WATER", amount = 3 },
      { instance = "ITFO_WINE", amount = 1 },
      { instance = "ITPO_HEALTH_01", amount = 1 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Citizen",
    description = "An ordinary townsman with simple clothes, a knife and enough coin for a short day outside the walls.",
    team = "City of Khorinis",
    strength = 20,
    dexterity = 20,
    mana = 0,
    health = 220,
    skills = {
      [WEAPON_1H] = 15,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 225.433, y = -127.677, z = -1433.39, angle = 85 },
    armor = "ITAR_VLK_L",
    primary = "ITMW_1H_VLK_DAGGER",
    items = {
      { instance = "ITFO_BREAD", amount = 4 },
      { instance = "ITFO_APPLE", amount = 4 },
      { instance = "ITFO_BACON", amount = 2 },
      { instance = "ITFO_WINE", amount = 2 },
      { instance = "ITFO_WATER", amount = 2 },
      { instance = "ITMI_LUTE", amount = 1 },
      { instance = "ITLSTORCH", amount = 1 },
      { instance = "ITMI_GOLD", amount = 25 },
    }
  },
  {
    name = "Militia",
    description = "A city guard with basic sword training, a militia crossbow and patrol supplies.",
    team = "City of Khorinis",
    strength = 60,
    dexterity = 45,
    mana = 0,
    health = 350,
    skills = {
      [WEAPON_1H] = 35,
      [WEAPON_2H] = 20,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 25
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 6800.71, y = 800, z = 8349.86, angle = 60 },
    armor = "ITAR_MIL_L",
    primary = "ITMW_1H_MIL_SWORD",
    secondary = "ITRW_MIL_CROSSBOW",
    items = {
      { instance = "ITRW_BOLT", amount = 40 },
      { instance = "ITKE_KEY_01", amount = 1 },
      { instance = "ITKE_KEY_02", amount = 1 },
      { instance = "ITKE_KEY_03", amount = 1 },
      { instance = "ITFO_BREAD", amount = 5 },
      { instance = "ITFO_BACON", amount = 3 },
      { instance = "ITFO_WATER", amount = 3 },
      { instance = "ITFO_WINE", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
    }
  },
  {
    name = "Elite Militia",
    description = "A veteran town guard issued heavier armor, a better blade and a stronger crossbow.",
    team = "City of Khorinis",
    strength = 100,
    dexterity = 90,
    mana = 0,
    health = 600,
    skills = {
      [WEAPON_1H] = 60,
      [WEAPON_2H] = 40,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 55
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 6800.71, y = 800, z = 8349.86, angle = 60 },
    armor = "ITAR_MIL_M",
    primary = "ITMW_SCHWERT4",
    secondary = "ITRW_CROSSBOW_M_02",
    items = {
      { instance = "ITRW_BOLT", amount = 60 },
      { instance = "ITKE_KEY_01", amount = 1 },
      { instance = "ITKE_KEY_02", amount = 1 },
      { instance = "ITKE_KEY_03", amount = 1 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITFO_WINE", amount = 3 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
    }
  },
  {
    name = "Knight",
    description = "A knight of Khorinis, strong in melee and carrying a small set of holy support magic.",
    team = "City of Khorinis",
    strength = 130,
    dexterity = 90,
    mana = 150,
    health = 850,
    skills = {
      [WEAPON_1H] = 75,
      [WEAPON_2H] = 70,
      [WEAPON_BOW] = 20,
      [WEAPON_CBOW] = 55
    },
    magicLevel = 3,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 11940.5, y = 950.005, z = -3314.08, angle = -53.5 },
    armor = "ITAR_PAL_M",
    primary = "ITMW_1H_PAL_SWORD",
    secondary = "ITRW_CROSSBOW_M_02",
    items = {
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITRU_TELEPORTPASSNW", amount = 1 },
      { instance = "ITRU_PALLIGHT", amount = 1 },
      { instance = "ITRU_PALLIGHTHEAL", amount = 1 },
      { instance = "ITSC_PALHOLYBOLT", amount = 3 },
      { instance = "ITRW_BOLT", amount = 60 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITPO_MANA_01", amount = 2 },
    }
  },
  {
    name = "Paladin",
    description = "A fully armed paladin with heavy armor, a blessed sword and reliable holy magic.",
    team = "City of Khorinis",
    strength = 160,
    dexterity = 120,
    mana = 300,
    health = 1050,
    skills = {
      [WEAPON_1H] = 90,
      [WEAPON_2H] = 85,
      [WEAPON_BOW] = 30,
      [WEAPON_CBOW] = 65
    },
    magicLevel = 5,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 11940.5, y = 950.005, z = -3314.08, angle = -53.5 },
    armor = "ITAR_PAL_H",
    primary = "ITMW_1H_BLESSED_02",
    secondary = "ITRW_CROSSBOW_H_01",
    items = {
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITRU_TELEPORTPASSNW", amount = 1 },
      { instance = "ITRU_PALLIGHT", amount = 1 },
      { instance = "ITRU_PALLIGHTHEAL", amount = 1 },
      { instance = "ITRU_PALHOLYBOLT", amount = 1 },
      { instance = "ITRU_PALREPELEVIL", amount = 1 },
      { instance = "ITSC_PALFULLHEAL", amount = 1 },
      { instance = "ITRW_BOLT", amount = 80 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_BACON", amount = 5 },
      { instance = "ITFO_WATER", amount = 5 },
      { instance = "ITPO_HEALTH_02", amount = 3 },
      { instance = "ITPO_MANA_02", amount = 3 },
    }
  },
  {
    name = "Lord",
    description = "A wealthy city lord with rare armor, a fine sword and enough supplies to stay protected.",
    team = "City of Khorinis",
    strength = 130,
    dexterity = 100,
    mana = 100,
    health = 900,
    skills = {
      [WEAPON_1H] = 70,
      [WEAPON_2H] = 50,
      [WEAPON_BOW] = 20,
      [WEAPON_CBOW] = 40
    },
    magicLevel = 2,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 16052.3, y = 950.005, z = -2377.6, angle = -83.4 },
    armor = "ITAR_OREBARON_ADDON",
    primary = "ITMW_SCHWERT5",
    items = {
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITMI_GOLD", amount = 150 },
      { instance = "ITMI_SEXTANT", amount = 1 },
      { instance = "ITMI_LUTE", amount = 1 },
      { instance = "ITFO_WINE", amount = 8 },
      { instance = "ITFO_BREAD", amount = 5 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITSC_INSTANTFIREBALL", amount = 3 },
    }
  },
  {
    name = "Governor",
    description = "A city official with formal clothes, coin and a ceremonial blade, not a battlefield kit.",
    team = "City of Khorinis",
    strength = 45,
    dexterity = 45,
    mana = 0,
    health = 450,
    skills = {
      [WEAPON_1H] = 25,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 15634.4, y = 1122.82, z = 109.455, angle = -47.3 },
    armor = "ITAR_GOVERNOR",
    primary = "ITMW_1H_VLK_DAGGER",
    items = {
      { instance = "ITMI_GOLD", amount = 200 },
      { instance = "ITMI_SEXTANT", amount = 1 },
      { instance = "ITMI_LUTE", amount = 1 },
      { instance = "ITFO_WINE", amount = 8 },
      { instance = "ITFO_BREAD", amount = 4 },
      { instance = "ITFO_WATER", amount = 3 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Farmer",
    description = "A farm worker with a mace, work clothes, yard tools and simple provisions.",
    team = "Onar's Farm",
    strength = 30,
    dexterity = 20,
    mana = 0,
    health = 260,
    skills = {
      [WEAPON_1H] = 25,
      [WEAPON_2H] = 20,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 71628.4, y = 3225.69, z = -10510.1, angle = -60.2 },
    armor = "ITAR_BAU_M",
    primary = "ITMW_1H_MACE_L_04",
    items = {
      { instance = "ITMI_RAKE", amount = 1 },
      { instance = "ITMI_SCOOP", amount = 1 },
      { instance = "ITMI_BROOM", amount = 1 },
      { instance = "ITMI_BRUSH", amount = 1 },
      { instance = "ITFO_BREAD", amount = 5 },
      { instance = "ITFO_CHEESE", amount = 3 },
      { instance = "ITFO_BACON", amount = 3 },
      { instance = "ITFO_WINE", amount = 2 },
      { instance = "ITFO_BEER", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 1 },
    }
  },
  {
    name = "Mercenary",
    description = "A new mercenary with light armor, a plain sword and practical field rations.",
    team = "Onar's Farm",
    strength = 65,
    dexterity = 45,
    mana = 0,
    health = 350,
    skills = {
      [WEAPON_1H] = 35,
      [WEAPON_2H] = 35,
      [WEAPON_BOW] = 25,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 75011.4, y = 3564.09, z = -12786.9, angle = 85 },
    armor = "ITAR_SLD_L",
    primary = "ITMW_1H_SWORD_L_03",
    secondary = "ITRW_BOW_L_01",
    items = {
      { instance = "ITRW_ARROW", amount = 40 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_CHEESE", amount = 3 },
      { instance = "ITFO_BACON", amount = 3 },
      { instance = "ITFO_WATER", amount = 3 },
      { instance = "ITFO_WINE", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITMI_JOINT", amount = 3 },
    }
  },
  {
    name = "Good Mercenary",
    description = "A proven mercenary with sturdier armor, a soldier blade and a reliable crossbow.",
    team = "Onar's Farm",
    strength = 110,
    dexterity = 80,
    mana = 0,
    health = 600,
    skills = {
      [WEAPON_1H] = 60,
      [WEAPON_2H] = 60,
      [WEAPON_BOW] = 35,
      [WEAPON_CBOW] = 45
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 75011.4, y = 3564.09, z = -12786.9, angle = 85 },
    armor = "ITAR_SLD_M",
    primary = "ITMW_1H_SLD_SWORD",
    secondary = "ITRW_CROSSBOW_L_02",
    items = {
      { instance = "ITRW_BOLT", amount = 60 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_CHEESE", amount = 4 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITFO_WINE", amount = 3 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITMI_JOINT", amount = 5 },
    }
  },
  {
    name = "Elite Mercenary",
    description = "A seasoned farm fighter in heavy armor, built around two-handed pressure and staying power.",
    team = "Onar's Farm",
    strength = 150,
    dexterity = 110,
    mana = 0,
    health = 900,
    skills = {
      [WEAPON_1H] = 75,
      [WEAPON_2H] = 85,
      [WEAPON_BOW] = 40,
      [WEAPON_CBOW] = 55
    },
    magicLevel = 0,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 75011.4, y = 3564.09, z = -12786.9, angle = 85 },
    armor = "ITAR_SLD_H",
    primary = "ITMW_SCHLACHTAXT",
    secondary = "ITRW_CROSSBOW_M_01",
    items = {
      { instance = "ITRW_BOLT", amount = 80 },
      { instance = "ITFO_BREAD", amount = 8 },
      { instance = "ITFO_CHEESE", amount = 5 },
      { instance = "ITFO_BACON", amount = 5 },
      { instance = "ITFO_WATER", amount = 5 },
      { instance = "ITFO_WINE", amount = 4 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITPO_HEALTH_03", amount = 2 },
      { instance = "ITMI_JOINT", amount = 6 },
    }
  },
  {
    name = "Dragon Hunter",
    description = "A young dragon hunter with light armor, a sturdy sword, a hunting bow and field medicine.",
    team = "Onar's Farm",
    strength = 120,
    dexterity = 100,
    mana = 0,
    health = 650,
    skills = {
      [WEAPON_1H] = 60,
      [WEAPON_2H] = 65,
      [WEAPON_BOW] = 55,
      [WEAPON_CBOW] = 35
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 1,
    spawn = { x = 72210.6, y = 3162.68, z = -10192.1, angle = 78.2 },
    armor = "ITAR_DJG_L",
    primary = "ITMW_SCHWERT5",
    secondary = "ITRW_BOW_M_02",
    items = {
      { instance = "ITRW_ARROW", amount = 70 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITPO_HEALTH_02", amount = 3 },
      { instance = "ITMI_JOINT", amount = 5 },
    }
  },
  {
    name = "Good Dragon Hunter",
    description = "An experienced dragon hunter with medium armor, a heavy axe and a strong bow.",
    team = "Onar's Farm",
    strength = 155,
    dexterity = 140,
    mana = 0,
    health = 900,
    skills = {
      [WEAPON_1H] = 75,
      [WEAPON_2H] = 85,
      [WEAPON_BOW] = 75,
      [WEAPON_CBOW] = 45
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 1,
    spawn = { x = 72210.6, y = 3162.68, z = -10192.1, angle = 78.2 },
    armor = "ITAR_DJG_M",
    primary = "ITMW_BARBARENSTREITAXT",
    secondary = "ITRW_BOW_H_02",
    items = {
      { instance = "ITRW_ARROW", amount = 90 },
      { instance = "ITMW_SCHLACHTAXT", amount = 1 },
      { instance = "ITFO_BREAD", amount = 8 },
      { instance = "ITFO_BACON", amount = 5 },
      { instance = "ITFO_WATER", amount = 5 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITPO_HEALTH_03", amount = 2 },
      { instance = "ITMI_JOINT", amount = 5 },
    }
  },
  {
    name = "Elite Dragon Hunter",
    description = "An elite dragon hunter with the best hunter armor, a brutal axe and a master bow.",
    team = "Onar's Farm",
    strength = 180,
    dexterity = 150,
    mana = 0,
    health = 1100,
    skills = {
      [WEAPON_1H] = 85,
      [WEAPON_2H] = 95,
      [WEAPON_BOW] = 85,
      [WEAPON_CBOW] = 55
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 1,
    spawn = { x = 72210.6, y = 3162.68, z = -10192.1, angle = 78.2 },
    armor = "ITAR_DJG_H",
    primary = "ITMW_BERSERKERAXT",
    secondary = "ITRW_BOW_H_03",
    items = {
      { instance = "ITRW_ARROW", amount = 100 },
      { instance = "ITFO_BREAD", amount = 8 },
      { instance = "ITFO_BACON", amount = 6 },
      { instance = "ITFO_WATER", amount = 6 },
      { instance = "ITPO_HEALTH_03", amount = 3 },
      { instance = "ITMI_JOINT", amount = 5 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Novice",
    description = "A monastery novice with light robes, a novice mace and basic fire scrolls.",
    team = "Monastery of Innos",
    strength = 25,
    dexterity = 25,
    mana = 220,
    health = 280,
    skills = {
      [WEAPON_1H] = 20,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 2,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 48808.3, y = 5042.76, z = 17211.5, angle = -32.3 },
    armor = "ITAR_NOV_L",
    primary = "ITMW_1H_NOV_MACE",
    items = {
      { instance = "ITRU_LIGHT", amount = 1 },
      { instance = "ITSC_FIREBOLT", amount = 8 },
      { instance = "ITSC_ZAP", amount = 4 },
      { instance = "ITSC_LIGHTHEAL", amount = 4 },
      { instance = "ITPO_MANA_01", amount = 5 },
      { instance = "ITPO_MANA_02", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITFO_BREAD", amount = 3 },
      { instance = "ITFO_WATER", amount = 3 },
    }
  },
  {
    name = "Fire Mage",
    description = "A fire mage with a focused spellbook, strong mana reserves and light mage robes.",
    team = "Monastery of Innos",
    strength = 35,
    dexterity = 35,
    mana = 650,
    health = 500,
    skills = {
      [WEAPON_1H] = 25,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 4,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 45934.2, y = 5042.76, z = 20100.2, angle = 30.7 },
    armor = "ITAR_KDF_L",
    primary = "ITMW_ADDON_STAB01",
    items = {
      { instance = "ITRU_TELEPORTMONASTERY", amount = 1 },
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITRU_LIGHT", amount = 1 },
      { instance = "ITRU_FIREBOLT", amount = 1 },
      { instance = "ITRU_INSTANTFIREBALL", amount = 1 },
      { instance = "ITRU_CHARGEFIREBALL", amount = 1 },
      { instance = "ITRU_FIRESTORM", amount = 1 },
      { instance = "ITSC_FULLHEAL", amount = 2 },
      { instance = "ITPO_MANA_02", amount = 6 },
      { instance = "ITPO_MANA_03", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITFO_WINE", amount = 2 },
    }
  },
  {
    name = "Arch Fire Mage",
    description = "An arch fire mage with master-level fire magic, high mana and emergency healing.",
    team = "Monastery of Innos",
    strength = 45,
    dexterity = 45,
    mana = 1050,
    health = 750,
    skills = {
      [WEAPON_1H] = 30,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 6,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 48435.4, y = 5042.76, z = 21970.3, angle = 28.6 },
    armor = "ITAR_KDF_H",
    primary = "ITMW_ADDON_STAB05",
    items = {
      { instance = "ITRU_TELEPORTMONASTERY", amount = 1 },
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITRU_LIGHT", amount = 1 },
      { instance = "ITRU_FIREBOLT", amount = 1 },
      { instance = "ITRU_INSTANTFIREBALL", amount = 1 },
      { instance = "ITRU_CHARGEFIREBALL", amount = 1 },
      { instance = "ITRU_FIRESTORM", amount = 1 },
      { instance = "ITRU_FIRERAIN", amount = 1 },
      { instance = "ITRU_PYROKINESIS", amount = 1 },
      { instance = "ITRU_FULLHEAL", amount = 1 },
      { instance = "ITPO_MANA_03", amount = 8 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITPO_SPEED", amount = 1 },
      { instance = "ITFO_WATER", amount = 5 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Water Novice",
    description = "A beginner in the Circle of Water with simple tools, light magic and travel supplies.",
    team = "Circle of Water",
    strength = 30,
    dexterity = 35,
    mana = 250,
    health = 300,
    skills = {
      [WEAPON_1H] = 20,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 10,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 2,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 83365.6, y = 3543.97, z = 28149.3, angle = -51 },
    armor = "ITAR_RANGER_ADDON",
    primary = "ITMW_1H_NOV_MACE",
    items = {
      { instance = "ITSC_LIGHT", amount = 2 },
      { instance = "ITSC_ZAP", amount = 3 },
      { instance = "ITSC_ICEBOLT", amount = 3 },
      { instance = "ITSC_LIGHTHEAL", amount = 3 },
      { instance = "ITSC_MEDIUMHEAL", amount = 1 },
      { instance = "ITPO_MANA_01", amount = 5 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITFO_FISH", amount = 3 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITMI_HAMMER", amount = 1 },
      { instance = "ITMI_RAKE", amount = 1 },
      { instance = "ITMI_BROOM", amount = 1 },
      { instance = "ITMI_BRUSH", amount = 1 },
    }
  },
  {
    name = "Water Mage",
    description = "A trained water mage with ice, lightning and healing runes backed by mana potions.",
    team = "Circle of Water",
    strength = 45,
    dexterity = 45,
    mana = 700,
    health = 550,
    skills = {
      [WEAPON_1H] = 30,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 4,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 83365.6, y = 3543.97, z = 28149.3, angle = -51 },
    armor = "ITAR_KDW_L_ADDON",
    primary = "ITMW_RANGERSTAFF_ADDON",
    items = {
      { instance = "ITRU_TELEPORTTAVERNE", amount = 1 },
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITRU_LIGHT", amount = 1 },
      { instance = "ITRU_ICEBOLT", amount = 1 },
      { instance = "ITRU_WATERFIST", amount = 1 },
      { instance = "ITRU_ICELANCE", amount = 1 },
      { instance = "ITRU_MEDIUMHEAL", amount = 1 },
      { instance = "ITRU_LIGHTNINGFLASH", amount = 1 },
      { instance = "ITSC_GEYSER", amount = 3 },
      { instance = "ITPO_MANA_02", amount = 6 },
      { instance = "ITPO_MANA_03", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITFO_FISH", amount = 4 },
      { instance = "ITFO_WATER", amount = 5 },
    }
  },
  {
    name = "Arch Water Mage",
    description = "A powerful archmage of water, commanding frost, storm and restoration magic.",
    team = "Circle of Water",
    strength = 55,
    dexterity = 55,
    mana = 1100,
    health = 800,
    skills = {
      [WEAPON_1H] = 35,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 6,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 83365.6, y = 3543.97, z = 28149.3, angle = -51 },
    armor = "ITAR_KDW_H",
    primary = "ITMW_ADDON_STAB05",
    items = {
      { instance = "ITRU_TELEPORTTAVERNE", amount = 1 },
      { instance = "ITRU_TELEPORTSEAPORT", amount = 1 },
      { instance = "ITRU_LIGHT", amount = 1 },
      { instance = "ITRU_ICECUBE", amount = 1 },
      { instance = "ITRU_ICEWAVE", amount = 1 },
      { instance = "ITRU_GEYSER", amount = 1 },
      { instance = "ITRU_WHIRLWIND", amount = 1 },
      { instance = "ITRU_THUNDERSTORM", amount = 1 },
      { instance = "ITRU_FULLHEAL", amount = 1 },
      { instance = "ITRU_LIGHTNINGFLASH", amount = 1 },
      { instance = "ITPO_MANA_03", amount = 8 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITPO_SPEED", amount = 1 },
      { instance = "ITFO_FISH", amount = 5 },
      { instance = "ITFO_WATER", amount = 5 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Rook",
    description = "A low-ranking bandit with a cheap sword, light bow and enough tricks to stay alive.",
    team = "Bandits",
    strength = 55,
    dexterity = 65,
    mana = 0,
    health = 350,
    skills = {
      [WEAPON_1H] = 35,
      [WEAPON_2H] = 15,
      [WEAPON_BOW] = 40,
      [WEAPON_CBOW] = 20
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 1,
    spawn = { x = 64073.2, y = 4000.27, z = -23874.8, angle = 60 },
    armor = "ITAR_BDT_M",
    primary = "ITMW_1H_VLK_SWORD",
    secondary = "ITRW_BOW_L_01",
    items = {
      { instance = "ITRW_ARROW", amount = 50 },
      { instance = "ITKE_LOCKPICK", amount = 4 },
      { instance = "ITMI_JOINT", amount = 5 },
      { instance = "ITFO_BREAD", amount = 5 },
      { instance = "ITFO_BACON", amount = 3 },
      { instance = "ITFO_BEER", amount = 3 },
      { instance = "ITLSTORCH", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
    }
  },
  {
    name = "Rogue",
    description = "An experienced bandit scout, faster and better with bows than most front-line fighters.",
    team = "Bandits",
    strength = 85,
    dexterity = 105,
    mana = 0,
    health = 550,
    skills = {
      [WEAPON_1H] = 55,
      [WEAPON_2H] = 30,
      [WEAPON_BOW] = 65,
      [WEAPON_CBOW] = 40
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 1,
    spawn = { x = 64073.2, y = 4000.27, z = -23874.8, angle = 60 },
    armor = "ITAR_BDT_H",
    primary = "ITMW_1H_SLD_SWORD",
    secondary = "ITRW_BOW_M_03",
    items = {
      { instance = "ITRW_ARROW", amount = 70 },
      { instance = "ITKE_LOCKPICK", amount = 6 },
      { instance = "ITMI_JOINT", amount = 8 },
      { instance = "ITFO_BREAD", amount = 6 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_BEER", amount = 4 },
      { instance = "ITLSTORCH", amount = 2 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
    }
  },
  {
    name = "Bandit",
    description = "A hardened camp fighter with solid armor, an axe and a crossbow for ambushes.",
    team = "Bandits",
    strength = 105,
    dexterity = 90,
    mana = 0,
    health = 600,
    skills = {
      [WEAPON_1H] = 60,
      [WEAPON_2H] = 50,
      [WEAPON_BOW] = 30,
      [WEAPON_CBOW] = 55
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 1,
    spawn = { x = 64073.2, y = 4000.27, z = -23874.8, angle = 60 },
    armor = "ITAR_BLOODWYN_ADDON",
    primary = "ITMW_1H_SLD_AXE",
    secondary = "ITRW_CROSSBOW_L_02",
    items = {
      { instance = "ITRW_BOLT", amount = 60 },
      { instance = "ITKE_LOCKPICK", amount = 5 },
      { instance = "ITMI_JOINT", amount = 8 },
      { instance = "ITFO_STEW", amount = 3 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_BEER", amount = 4 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
    }
  },
  {
    name = "Shadow",
    description = "The boss's trusted hand, trained for stealth, bow work and decisive close combat.",
    team = "Bandits",
    strength = 120,
    dexterity = 135,
    mana = 0,
    health = 800,
    skills = {
      [WEAPON_1H] = 70,
      [WEAPON_2H] = 45,
      [WEAPON_BOW] = 75,
      [WEAPON_CBOW] = 55
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 1,
    spawn = { x = 64073.2, y = 4000.27, z = -23874.8, angle = 60 },
    armor = "ITAR_DIEGO",
    primary = "ITMW_1H_SPECIAL_03",
    secondary = "ITRW_BOW_M_03",
    items = {
      { instance = "ITRW_ARROW", amount = 80 },
      { instance = "ITKE_LOCKPICK", amount = 8 },
      { instance = "ITMI_JOINT", amount = 10 },
      { instance = "ITFO_STEW", amount = 4 },
      { instance = "ITFO_BACON", amount = 5 },
      { instance = "ITFO_BEER", amount = 5 },
      { instance = "ITPO_HEALTH_02", amount = 3 },
      { instance = "ITPO_SPEED", amount = 1 },
    }
  },
  {
    name = "Elite Bandit",
    description = "An elite enforcer in Thorus armor, heavy enough to hold a line and dirty enough to raid it.",
    team = "Bandits",
    strength = 150,
    dexterity = 120,
    mana = 0,
    health = 900,
    skills = {
      [WEAPON_1H] = 80,
      [WEAPON_2H] = 75,
      [WEAPON_BOW] = 45,
      [WEAPON_CBOW] = 70
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 1,
    spawn = { x = 64073.2, y = 4000.27, z = -23874.8, angle = 60 },
    armor = "ITAR_THORUS_ADDON",
    primary = "ITMW_SCHWERT5",
    secondary = "ITRW_CROSSBOW_H_01",
    items = {
      { instance = "ITRW_BOLT", amount = 80 },
      { instance = "ITKE_LOCKPICK", amount = 6 },
      { instance = "ITMI_JOINT", amount = 10 },
      { instance = "ITFO_STEW", amount = 4 },
      { instance = "ITFO_BACON", amount = 5 },
      { instance = "ITFO_BEER", amount = 5 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITPO_HEALTH_03", amount = 2 },
    }
  },
  {
    name = "Chief of Bandits",
    description = "The bandit boss, heavily armored and armed like a warlord without pretending to be a mage.",
    team = "Bandits",
    strength = 175,
    dexterity = 150,
    mana = 0,
    health = 1050,
    skills = {
      [WEAPON_1H] = 90,
      [WEAPON_2H] = 90,
      [WEAPON_BOW] = 55,
      [WEAPON_CBOW] = 80
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 1,
    spawn = { x = 64073.2, y = 4000.27, z = -23874.8, angle = 60 },
    armor = "ITAR_RAVEN_ADDON",
    primary = "ITMW_2H_SPECIAL_04",
    secondary = "ITRW_CROSSBOW_H_02",
    items = {
      { instance = "ITRW_BOLT", amount = 100 },
      { instance = "ITKE_LOCKPICK", amount = 8 },
      { instance = "ITMI_JOINT", amount = 10 },
      { instance = "ITFO_STEW", amount = 5 },
      { instance = "ITFO_BACON", amount = 6 },
      { instance = "ITFO_BEER", amount = 6 },
      { instance = "ITFO_WINE", amount = 3 },
      { instance = "ITPO_HEALTH_03", amount = 3 },
      { instance = "ITPO_SPEED", amount = 1 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Pirate",
    description = "A novice pirate with a cutlass, light bow, fish and a few bottles from camp.",
    team = "Pirates",
    strength = 60,
    dexterity = 60,
    mana = 0,
    health = 350,
    skills = {
      [WEAPON_1H] = 35,
      [WEAPON_2H] = 20,
      [WEAPON_BOW] = 35,
      [WEAPON_CBOW] = 15
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 0,
    spawn = { x = -3783.1, y = -588.972, z = 12239.2, angle = -84.4 },
    armor = "ITAR_PIR_L_ADDON",
    primary = "ITMW_ADDON_PIR1HSWORD",
    secondary = "ITRW_BOW_L_02",
    items = {
      { instance = "ITRW_ARROW", amount = 50 },
      { instance = "ITFO_FISH", amount = 5 },
      { instance = "ITFO_BREAD", amount = 4 },
      { instance = "ITFO_WATER", amount = 3 },
      { instance = "ITFO_ADDON_RUM", amount = 4 },
      { instance = "ITFO_ADDON_GROG", amount = 4 },
      { instance = "ITFO_ADDON_LOUSHAMMER", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
    }
  },
  {
    name = "Elite Pirate",
    description = "The captain's right hand, dangerous with a crooked blade and a heavy crossbow.",
    team = "Pirates",
    strength = 145,
    dexterity = 130,
    mana = 0,
    health = 800,
    skills = {
      [WEAPON_1H] = 75,
      [WEAPON_2H] = 60,
      [WEAPON_BOW] = 50,
      [WEAPON_CBOW] = 70
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 0,
    spawn = { x = -3783.1, y = -588.972, z = 12239.2, angle = -84.4 },
    armor = "ITAR_PIR_M_ADDON",
    primary = "ITMW_KRUMMSCHWERT",
    secondary = "ITRW_CROSSBOW_H_01",
    items = {
      { instance = "ITRW_BOLT", amount = 80 },
      { instance = "ITFO_FISH", amount = 6 },
      { instance = "ITFO_BACON", amount = 4 },
      { instance = "ITFO_WATER", amount = 4 },
      { instance = "ITFO_ADDON_RUM", amount = 6 },
      { instance = "ITFO_ADDON_GROG", amount = 6 },
      { instance = "ITFO_ADDON_LOUSHAMMER", amount = 4 },
      { instance = "ITPO_HEALTH_02", amount = 3 },
      { instance = "ITPO_HEALTH_03", amount = 1 },
    }
  },
  {
    name = "Captain of Pirates",
    description = "The pirate captain, fully armed for raids and stocked with the crew's best provisions.",
    team = "Pirates",
    strength = 165,
    dexterity = 150,
    mana = 0,
    health = 1000,
    skills = {
      [WEAPON_1H] = 90,
      [WEAPON_2H] = 80,
      [WEAPON_BOW] = 55,
      [WEAPON_CBOW] = 85
    },
    magicLevel = 0,
    acrobatics = 1,
    sneaking = 1,
    lockpicking = 1,
    pickpocket = 0,
    spawn = { x = -3783.1, y = -588.972, z = 12239.2, angle = -84.4 },
    armor = "ITAR_PIR_H_ADDON",
    primary = "ITMW_KRUMMSCHWERT",
    secondary = "ITRW_CROSSBOW_H_02",
    items = {
      { instance = "ITRW_BOLT", amount = 100 },
      { instance = "ITFO_FISH", amount = 8 },
      { instance = "ITFO_BACON", amount = 5 },
      { instance = "ITFO_WATER", amount = 5 },
      { instance = "ITFO_ADDON_RUM", amount = 8 },
      { instance = "ITFO_ADDON_GROG", amount = 8 },
      { instance = "ITFO_ADDON_LOUSHAMMER", amount = 5 },
      { instance = "ITMI_SEXTANT", amount = 1 },
      { instance = "ITPO_HEALTH_03", amount = 3 },
      { instance = "ITPO_SPEED", amount = 1 },
    }
  },
  --[[ =============================================================================== ]]--
  {
    name = "Dark Novice",
    description = "A shadow pawn with basic dark magic, light armor and a simple sword.",
    team = "Dark Mages",
    strength = 35,
    dexterity = 35,
    mana = 300,
    health = 320,
    skills = {
      [WEAPON_1H] = 20,
      [WEAPON_2H] = 20,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 3,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 29958.9, y = 5955.16, z = -15831.6, angle = 2 },
    armor = "ITAR_LESTER",
    primary = "ITMW_1H_SWORD_L_03",
    items = {
      { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
      { instance = "ITRU_FIREBOLT", amount = 1 },
      { instance = "ITRU_ZAP", amount = 1 },
      { instance = "ITSC_FEAR", amount = 3 },
      { instance = "ITSC_SUMGOBSKEL", amount = 2 },
      { instance = "ITPO_MANA_01", amount = 5 },
      { instance = "ITPO_MANA_02", amount = 2 },
      { instance = "ITPO_HEALTH_01", amount = 2 },
      { instance = "ITFO_FISH", amount = 2 },
      { instance = "ITFO_APPLE", amount = 2 },
      { instance = "ITFO_WATER", amount = 2 },
    }
  },
  {
    name = "Dark Warrior",
    description = "A warrior of darkness with brutal weapons, strong mana reserves and combat runes.",
    team = "Dark Mages",
    strength = 110,
    dexterity = 80,
    mana = 600,
    health = 700,
    skills = {
      [WEAPON_1H] = 60,
      [WEAPON_2H] = 65,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 4,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 29958.9, y = 5955.16, z = -15831.6, angle = 2 },
    armor = "ITAR_CORANGAR",
    primary = "ITMW_2H_ORCAXE_03",
    items = {
      { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
      { instance = "ITRU_FIREBOLT", amount = 1 },
      { instance = "ITRU_WINDFIST", amount = 1 },
      { instance = "ITRU_LIGHTHEAL", amount = 1 },
      { instance = "ITRU_ICECUBE", amount = 1 },
      { instance = "ITSC_FIRESTORM", amount = 3 },
      { instance = "ITSC_SLEEP", amount = 2 },
      { instance = "ITPO_MANA_02", amount = 5 },
      { instance = "ITPO_MANA_03", amount = 2 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITFO_SAUSAGE", amount = 3 },
      { instance = "ITFO_CHEESE", amount = 3 },
      { instance = "ITMI_JOINT", amount = 3 },
    }
  },
  {
    name = "Seeker",
    description = "A shadow mage armed with forbidden runes and a blessed two-handed blade.",
    team = "Dark Mages",
    strength = 120,
    dexterity = 90,
    mana = 950,
    health = 850,
    skills = {
      [WEAPON_1H] = 70,
      [WEAPON_2H] = 75,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 6,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 29958.9, y = 5955.16, z = -15831.6, angle = 2 },
    armor = "ITAR_DEMENTOR",
    primary = "ITMW_2H_BLESSED_03",
    items = {
      { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
      { instance = "ITRU_PYROKINESIS", amount = 1 },
      { instance = "ITRU_SLEEP", amount = 1 },
      { instance = "ITRU_ICEWAVE", amount = 1 },
      { instance = "ITRU_SKULL", amount = 1 },
      { instance = "ITRU_BREATHOFDEATH", amount = 1 },
      { instance = "ITPO_MANA_03", amount = 6 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITFO_FISH", amount = 3 },
      { instance = "ITFO_APPLE", amount = 3 },
      { instance = "ITMI_JOINT", amount = 3 },
    }
  },
  {
    name = "Necromancer",
    description = "A necromancer in Xardas robes, physically fragile but built around forbidden master magic.",
    team = "Dark Mages",
    strength = 50,
    dexterity = 50,
    mana = 1200,
    health = 800,
    skills = {
      [WEAPON_1H] = 25,
      [WEAPON_2H] = 0,
      [WEAPON_BOW] = 0,
      [WEAPON_CBOW] = 0
    },
    magicLevel = 6,
    acrobatics = 0,
    sneaking = 0,
    lockpicking = 0,
    pickpocket = 0,
    spawn = { x = 29958.9, y = 5955.16, z = -15831.6, angle = 2 },
    armor = "ITAR_XARDAS",
    primary = "ITMW_ADDON_STAB05",
    items = {
      { instance = "ITRU_TELEPORTXARDAS", amount = 1 },
      { instance = "ITRU_LIGHT", amount = 1 },
      { instance = "ITRU_SUMSKEL", amount = 1 },
      { instance = "ITRU_SUMDEMON", amount = 1 },
      { instance = "ITRU_BREATHOFDEATH", amount = 1 },
      { instance = "ITRU_MASSDEATH", amount = 1 },
      { instance = "ITRU_ARMYOFDARKNESS", amount = 1 },
      { instance = "ITRU_FULLHEAL", amount = 1 },
      { instance = "ITPO_MANA_03", amount = 8 },
      { instance = "ITPO_HEALTH_02", amount = 2 },
      { instance = "ITFO_FISH", amount = 3 },
      { instance = "ITFO_APPLE", amount = 3 },
    }
  },
}

return Classic
